title: The Wealth of Destitution
url: "https://wealthofdestitution.com"
author:
  name: Dane Holmes
  email: d@dane.cc
description: >
  A work-in-progress novel.

# Build settings
theme: wealthy

collections:
  chapters:
    output: fasle
    permalink: :collection/:name

wealthy:
  date_format: "%b %-d, %Y"

social:
  name: Dane Holmes
  links:
    - https://twitter.com/daneholmes
    - https://www.linkedin.com/in/daneholmes
    - https://github.com/daneholmes
    - https://www.instagram.com/dane.holmes

twitter:
  username: daneholmes
  card: summary

plugins:
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jekyll-sitemap
